AppBundle\Entity\TblFollowing:
    type: entity
    table: tbl_following
    indexes:
        identifier:
            columns:
                - identifier
        webSiteURL:
            columns:
                - webSiteURL
        profileURL:
            columns:
                - profileURL
        photoURL:
            columns:
                - photoURL
        displayName:
            columns:
                - displayName
        description:
            columns:
                - description
        email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        identifier:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        websiteurl:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: webSiteURL
        profileurl:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: profileURL
        photourl:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: photoURL
        displayname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: displayName
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        response:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
